### PR TITLE
Add developer guide with release guide

### PR DESCRIPTION
**Pull request by geigerzaehler**
Add a developer guide that explains how to release this project. We can add more information if needed

### CODE REVIEW

**Comment by geigerzaehler** [comment]
>  So in 3, the message is essentially the same as in 4 (except for the header maybe)?

Yes, it’s the same but for the title. Is there a need to clarify some more in the document? Maybe move the example from 4. to 3. and just reference it in 4.?

**Comment by wisp3rwind** [comment]
> Yes, it’s the same but for the title. Is there a need to clarify some more in the document? Maybe move the example from 4. to 3. and just reference it in 4.?

I think it's quite clear already, but if I were to make a release, I would have searched for old release commits to make sure I understood this correctly. By referencing the example (or even duplicating it with the different headers?), I wouldn't have had to check. Not a big issue all in all, so feel free to ignore this request :)

**Comment by geigerzaehler** [comment]
I’ve adjusted the guide a bit: I does not make sense to have the change log entries in the commit that creates the release so I’ve removed that. Now the explanation of the tag annotation  should be clearer.

**Comment by wisp3rwind** [comment]
Sounds good!

**Pull request merged**
